---
output: 
  html_document: 
    theme: readable
---

# Syllabus for Math 253
# Statistical Computing and Machine Learning
## Spring 2017 


* Instructor: **Danny Kaplan**, Olin-Rice 231, `kaplan@macalester.edu`
* Office Hours: 
    - Tues and Thurs: 3:00pm-4:30pm and 
    - Wed: 2:00pm-3:30pm
    - Anytime by appointment. And if my office door is open, just drop in.
* Preceptor: **Yifan (Eva) Gong** `ygong@macalester.edu`
    - Wed 8:00pm-10:00pm, MSCS reading room. 
    - Thurs 7:00pm - 9:30pm, OLRI 245
* Text: [An Introduction to Statistical Learning](http://www.springer.com/us/book/9781461471370).  The authors also provide [access via PDF](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20First%20Printing.pdf).
* **Class notes**. [In-class notes for the entire semester](Class_notes/_book/introduction.html). (An evolving document.)
* An [introduction to R/RStudio/Markdown](http://ismayc.github.io/rbasics-book)
* A [introduction to git and GitHub](http://happygitwithr.com/classroom-overview.html) oriented to the classroom.
* The registrar has scheduled our **final exam** for Friday May 5 at 1:30pm - 3:30pm. 

### Starting the semester

* [Course policies](policies.html)
* [Installing and using GitHub from RStudio](github.html)
* Make an account on <GitHub.com> and enter your account ID and the corresponding email address on [this form](https://docs.google.com/forms/d/e/1FAIpQLSdEMEn_uHkv4Wm3BDYZ4TU_XxrrSVfXlQ5S7NK0vZvTTm5u-Q/viewform).

### Due dates

You should "push" your daily programming activity to your repository *before* leaving class. But feel free to revise your work and push again at any time.

Each topic assignment is due one week *after* we finish covering that topic in class.

- Topic I: Thurs Feb 9, 2017
- Topic II: Thurs Feb 16, 2017
- Topic III: Thurs March 2, 2017
- Topic IV: Tues March 28, 2017
- Topic V: TBA
- Remaining work: By the end of exam period.

## Topic I --- Introduction

* Topics
    - Overview of statistical learning.
    - Getting started with R, RStudio, and RMarkdown
* Reading: Chapter 2 of ISL
* Programming basics 1: Names, classes, and objects
* Assignment 1 --- file `Topic-1.Rmd`
    * Discussion questions: ISL 2.4.1, 2.4.3, 2.4.6
    * Computing assignment: ISL 2.4.8, 2.4.9
        - As an example: [a solution to 2.4.10](Assignments/ISL-2/example-week-2-programming.html).
    * Theory assignment: ISL 2.4.2, 2.4.7.
* Programming activities: [One (Jan 24)](ProgrammingActivities/Day-01-Programming-Task.html), [Two (Jan 29)](ProgrammingActivities/Day-02-Programming-Task.html), [Three (Jan 31)](ProgrammingActivities/Day-03-Programming-Task.html)

## Topic 2 --- Linear regression

* Readings.
    - In Chapter 3 of ISL read §3.1 & §3.2
    - Read §3.6 as you work through the commands (see computing assignment)
* Programming basics 2: 
    - Writing functions
    - Visualization: Base graphics, statistical plots
* Assignment 2 --- file `Topic-2.Rmd`
    - Computing
        - work through §3.6. (Style catastrophe: Although the book uses attach(), it is bad practice to do so. Ask about alternatives!)
        - Problem 13 in ISL 3.7.13.
    - Theory 
        - Reading questions.
            1. On p. 66 the authors state, "This is clearly not true in Fig. 3.1" Explain why.
            2. On p. 77 the authors state, "In this case we cannot even fit the multiple regression models using least squares ...." Explain why.
        - ISL 3.7.3 and 3.7.4.
* Programming activities: [Four (Feb 2)](ProgrammingActivities/Day-04-Programming-Task.html), [Five (Feb 7)](ProgrammingActivities/Day-05-Programming-Task.html), [Six (Feb 14)](ProgrammingActivities/Day-06-Programming-Task.html)


## Topic 3 --- Foundations: Linear Algebra, Bayes' Rule, and Likelihood

* Readings
    - These topics are not covered in ISLR, so no readings from the textbook.
    - Michael Lavine: "What is Bayesian statistics and why everything else is wrong" [PDF](Resources/Likelihood-Lavine.pdf)
* Programming basics 3: Conditionals
* Visualization: Base graphics: lines, polygons, ...
* Programming Activities: [Seven (Feb 16)](ProgrammingActivities/Day-07-Programming-Task.html), [Eight (Feb 21)](ProgrammingActivities/Day-08-Programming-Task.html), [Nine (Feb 23)](ProgrammingActivities/Day-09-Programming-Task.html)
* Topic assignment: there are no exercises from the textbook, so ... finish the exponential likelihood and taxicab in-class activities. 

## Topic 4 --- Classification

* Readings: In Chapter 4 of ISL §4.1, §4.2, §4.3.1-3, §4.4.1-2, §4.5
* Visualization: Grammar of graphics: glyphs and aesthetics
* Topic 4 Assignment:
    - Programming Assignment: 4.7.11, 4.7.13
    - Theory assignment: 4.7.1, 4.7.8, 4.7.9
* Programming Activities: [Ten (Feb 28)](ProgrammingActivities/Day-10-Programming-Task.html), [Eleven (March 2)](ProgrammingActivities/Day-11-Programming-Task.html), [Twelve (March 7)](ProgrammingActivities/Day-12-Programming-Task.html)


## Topic 5 --- Cross-validation and bootstrapping

* Readings: In Chapter 5 of ISL §5.1, §5.2
* Programming basics 5: Loops and accumulators
* Assignment: finish the in-class programming activities for the first five topics.
* Programming Activity: [Thirteen - Mar 23](ProgrammingActivities/Day-13-Programming-Task.html)

## Topic 6 --- Selecting model terms

* Readings: in Chapter 6 of ISL §6.1, §6.2
* Programming basics 6: Functionals --- solving, integration, optimization
* Assignment: 
    - Theory 6.8.1, 6.8.2. 
    - Applied, 6.8.9
* Programming Activities: [Fourteen](ProgrammingActivities/Day-14-Programming-Task.pdf), [Fifteen](ProgrammingActivities/Day-15-Programming-Task.pdf)

## Topic 7 --- Nonlinear regression

* Readings: Chapter 7 of ISL
* Assignment:
    - programming: 7.9.11
    - theory: in §7.9 problems 3, 4, and 5
* Programming Activity: [Sixteen](ProgrammingActivities/Day-16-Programming-Task.pdf)
 
## Topic 8 --- Tree-based methods

* Readings: Chapter 8 of ISL
* Assignment:
    - programming: 8.4.12
    - theory: In §8.4 problems 1, 2, 3, 4, and 5
* Programming Activity: [Seventeen](ProgrammingActivities/Day-17-Programming-Task.pdf)

## Topic 9 --- Support vector machines

* Readings: Chapter 9 of ISL
* Programming Activity: [Eighteen](ProgrammingActivities/Day-18-Programming-Task.pdf)

## Topic 10 --- Unsupervised learning

* Readings: Chapter 10 of ISL



## End-of-term Project

In the few weeks of the course, the class will be working on end-of-term projects. You do not need to do anything before that time arrives.

* You'll form groups of two to three students and choose a problem from the Kaggle machine-learning competition site. You don't need to think about this until we get toward the end of the semester. At that point, the in-class programming activities will be given over to the project.
* If you have your own idea for a project, please get my approval before embarking on it.
* [Course-project topic selection](https://docs.google.com/spreadsheets/d/1_9j27pURZTR07kC0n-FcIirJ2PZ2K8NwJGkOrwfL-gY/edit?usp=sharing)
* [Course project report rubric](Assignments/Kaggle-project-rubric.html)


------------------

*Updated Jan 12, 2017*
