---
title: "Preface"
author: 'Math 253: Statistical Computing & Machine Learning'
date: "Starting out in R"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    latex_engine: xelatex
  tufte::tufte_book:
    latex_engine: xelatex
---

## Math 253 and the Macalester statistics curriculum {-}

Math 253, Statistical Computing and Machine Learning, is a course at [Macalester College](http://www.macalester.edu). The course comes early in our curriculum for the statistics major. Currently, that curriculum looks like:

1. Comp 110, [Data Computing](Data-Computing.org), a no-prerequisite course in data wrangling and visualization. The main tools in the course are R, dplyr, and ggplot.
2. Math 125, Epidemiology. This course also has no pre-requisites. It's designed to teach quantitative and statistical literacy in the context of public health and decision making. Unlike the other courses in our curriculum, Math 125 is *not* computer intensive. This is an *elective* for the statistics major.
3. Math 155, [Introduction to Statistical Modeling](http://www.mosaic-web.org/StatisticalModeling). This is our main entry-level statistics course. It also has no pre-requisites, but we encourage students to take a course in our calculus sequence: Applied Multivariate Calculus I, II, and III. The course covers important concepts in modeling: model architectures and fitting using mainly linear and logistic regression, covariation and adjustment, interpretation of model coefficients, inference techniques such as analysis of variance and co-variance and the ways these techniques can inform the decisions needed to build useful models, causality including techniques for making reasonable conclusions about causation from observational data. The course makes very extensive and intensive use of R and the [`mosaic`](https://cran.r-project.org/web/packages/mosaic/vignettes/LessVolume-MoreCreativity.html) package for R.
4. This course, **Math 253, Statistical Computing and Machine Learning**. Math 253 introduces a broader set of model architectures (e.g. those associated with "machine learning" such as support vector machines) and the trade-offs that make machine learning a human skill rather than a push button mechanism. The main text is [Introduction to Statistical Learning in R](http://www-bcf.usc.edu/~gareth/ISL/). Computing in R is used intensively in the course. Math 155 is a pre-requisite. The computing used in that course is the only pre-requisite. A small part of Math 253 is given to basic programming in R, but the large majority is about the mathematical and statistical concepts involved in learning from data and the exercise of a variety of architectures for classification and regression models.
    
    Math 253 is placed intentionally in the middle of our statistics curriculum to make it accessible to many students who are interested and may have use for the techniques, but whom are not primarily interested in statistics *per se*.
5. Upper level courses including:
    - Math 454: Bayesian statistics
    - Math 453: Biostatistics
    - Math 454: Mathematical statistics
6. Supporting courses including:
    - Math 354: Probability
    - Math 135: Applied Multivariate Calculus I 
    - Math 236: Linear algebra
    - Comp 123: Core conceptsin computer science
7. Electives such as
    - Math 432: Mathematical modeling
    - Math/Comp 365: Numerical linear algebra
    - Comp 302: Introduction to database management systems

## These notes ~~are~~ were written in Bookdown  {-}

Originally, these notes were produced in an elaboration on R/Markdown, called "[Bookdown](http://bookdown.org)."  That turned out not to be a good decision for this site, so now the notes are organized using a website project in RStudio.

