# (PART) Topic I: Linear Regression {-}


{#linear-regression}



```{r include=FALSE}
library(mosaic)
library(dplyr)
library(ggplot2)
```

## Day 4 Preview

* The linear model (e.g. what `lm()` does)
* A variety of questions relevant to different purposes, e.g.
    - how good will a prediction be?
    - what's the strength of an effect?
    - is there synergy between different factors?


ISL book's statement on why to study linear regression

> "Though it may seem somewhat dull compared to some of the more modern statistical learning approaches described ... later ..., linear regression is still a useful and widely used statistical learning method.  Moreover, it serves as a good jumping-off point for newer approaches....  Consequently, the importance of having a good understanding of linear regression before studying more complex learning methods cannot be overstated."

Concepts from linear regression:

* Compact representation of model form: polynomial coefficients.
* Much of inference (confidence intervals, hypothesis tests) can be expressed in terms of a polynomial coefficient.
* "Size" of model quantifiable as an integer: number of coefficients: degrees of freedom.
* Highly efficient estimation (when doing least squares)


## Small data

The regression techniques were developed in an era of small data, such as that that might be written in a lab notebook or field journal.  As a result:

1. Emphasis on very simple descriptions, such as means, differences between means, simple regression.
2. Theoretical concern with details of distributions, such as the t-distribution.
    - the difference between z- and t-distributions are of no consequence for moderate DF and higher.
3. No division into training and testing data.  Data are too valuable to test! (Ironic, given the importance of replicability in the theory of the scientific method.)

As a consequence of (3), there's a great deal of concern about *assumptions*, e.g.

* linearity of $f({\mathbf X})$
* structure of $\epsilon$: IID --- Independent and Identically Distributed
    - uncorrelated between cases
    - each is a draw from the same distribution.

